export const INCREMENT_REQUEST = "INCREMENT_REQUEST";
export const INCREMENT_SUCCESSED = "INCREMENT_SUCCESSED";

export const DECREMENT_REQUEST = "DECREMENT_REQUEST";
export const DECREMENT_SUCCESSED = "DECREMENT_SUCCESSED";

export const MULTI_REQUEST = "MULTI_REQUEST";
export const MULTI_SUCCEED = "MULTI_SUCCEED";

export const RESET_REQUEST = "RESET_REQUEST";
export const RESET_SUCCEED = "RESET_SUCCEED";

export const TEXT_REQUEST = "TEXT_REQUEST";
export const TEXT_SUCCEED="TEXT_SUCCEED";

export const INPUT_REQUEST = "INPUT_REQUEST";
export const INPUT_SUCCEED = "INPUT_SUCCEED";

